services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_and_push_container_image.sh to retrieve the digest.
    image: ghcr.io/talos-agent/talos:latest-agent@sha256:d82a5884ad0e747bb4a501485b9dfd874669a781ecf272d74c006ab5a6219b98
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
    volumes:
      - talos_data:/app/data
    ports:
      - "8000:8000"

volumes:
  talos_data:
