services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_and_push_container_image.sh to retrieve the digest.
    image: ghcr.io/talos-agent/talos:latest-agent@sha256:fc76d1cffa9f33e8536be447ec79f2acd1a60b3eaf79200be2c10c93a689ded8
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app/data/talos_data.db}
    volumes:
      - talos_data:/app/data
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    ports:
      - "8000:8000"

volumes:
  talos_data:
