"""add chainlink bridging

Revision ID: 2d1832776538
Revises: 54a4e7fb3a17
Create Date: 2025-09-12 17:08:02.426767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1832776538'
down_revision: Union[str, None] = '54a4e7fb3a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chainlink_bridges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_chain_id', sa.Integer(), nullable=False),
    sa.Column('dest_chain_id', sa.Integer(), nullable=False),
    sa.Column('recipient_address', sa.String(length=42), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chainlink_bridges')
    # ### end Alembic commands ###
