"""add swaps

Revision ID: 48f62aff9aa9
Revises: d7ca3e4695b8
Create Date: 2025-09-10 00:07:44.965094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f62aff9aa9'
down_revision: Union[str, None] = 'd7ca3e4695b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=78), nullable=False),
    sa.Column('token_in', sa.String(length=42), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=78), nullable=False),
    sa.Column('token_out', sa.String(length=42), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swaps')
    # ### end Alembic commands ###
