"""add tx_hash to swaps

Revision ID: 54a4e7fb3a17
Revises: 48f62aff9aa9
Create Date: 2025-09-10 03:24:50.980377

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54a4e7fb3a17"
down_revision: Union[str, None] = "48f62aff9aa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("swaps", sa.Column("transaction_hash", sa.String(length=66), nullable=False))
    op.add_column("swaps", sa.Column("chain_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("swaps", "transaction_hash")
    op.drop_column("swaps", "chain_id")
    # ### end Alembic commands ###
